In [4]:
import src.generation.gamma as ga
import src.generation.multivariate_normal as mn

from src.salp.salp import SALP

import numpy as np
import matplotlib.pyplot as plt

## Example pipeline

In [7]:
def pipeline(F: int, N: int, size: int, cor: float, rng = (2,4)):
    
    generator = ga.Generator(F, size, cor, rng)
    estimated_load = generator.get_estimated_cloud_load()
    estimated_minimal_node_power = estimated_load/size/N
    print(estimated_minimal_node_power)
    
    cloud = SALP(N, generator.generate_cloud_load_vectors())
    assert len(cloud.nodes) == N
    
    
pipeline(10, 2, 4, 0.5)

30.0
	Shards: [[ 8.45152739  9.67909248 14.92750306  9.71791405]
 [ 1.54353149  0.94444697 10.50500172  3.63569461]
 [ 3.30670885  5.24975723  5.54959148  6.26896354]
 [ 0.77163662  3.93228587  8.81758396  2.70738023]
 [ 4.95987705  5.03906559  7.18351862  7.60039981]
 [ 0.          4.90767208 11.14506277  5.40050643]
 [ 2.80594159  2.19791303  4.3288817   2.74613174]
 [ 0.          1.34794102 20.62155086 22.66587172]
 [ 3.08542678  3.11249792  3.24366247  3.17131131]
 [ 1.67430713  9.89621563 12.68850561 14.96205947]]

	WTS: [26.59895691 46.30688782 99.01086226 78.87623292]

	NWTS: [13.29947846 23.15344391 49.50543113 39.43811646]

	LW: [(7, 30.672578076172176), (9, 22.03632878890605), (0, 21.963181635496422), (5, 13.32152915816117), (4, 12.62384963175082), (1, 11.262673130641721), (2, 10.420755439344855), (3, 10.056738524649123), (8, 6.307619470859597), (6, 6.243763788540718)]

	
7
Shard: [ 0.          1.34794102 20.62155086 22.66587172]
Node: 0
Delta: 26.648872590589086


Shard: [ 0

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

# Parametry dla iteracji
* F - ilość shardów
* N - ilość węzłów
* cor - poziom korelacji miedzy wektorami obciążenia
* ro - poziom obciążenia chmury
* size - długość wektorów obciążenia
* parametry generatora do ustalenia